create table "public"."logs" (
    "date" text not null,
    "trainingId" bigint not null,
    "memberId" bigint not null,
    "isMainTrainer" boolean not null default false
);


alter table "public"."logs" enable row level security;

create table "public"."members" (
    "id" bigint generated by default as identity not null,
    "lastname" text not null,
    "firstname" text not null,
    "birthday" text,
    "mobile" text,
    "img" text,
    "labels" jsonb
);


alter table "public"."members" enable row level security;

create table "public"."participants" (
    "trainingId" bigint generated by default as identity not null,
    "memberId" bigint not null
);


alter table "public"."participants" enable row level security;

create table "public"."trainings" (
    "id" bigint generated by default as identity not null,
    "title" text,
    "section" text,
    "weekday" text,
    "dateFrom" text,
    "dateTo" text
);


alter table "public"."trainings" enable row level security;

CREATE UNIQUE INDEX logs_pkey ON public.logs USING btree (date, "trainingId", "memberId");

CREATE UNIQUE INDEX members_pkey ON public.members USING btree (id);

CREATE UNIQUE INDEX participants_pkey ON public.participants USING btree ("trainingId", "memberId");

CREATE UNIQUE INDEX trainings_pkey ON public.trainings USING btree (id);

alter table "public"."logs" add constraint "logs_pkey" PRIMARY KEY using index "logs_pkey";

alter table "public"."members" add constraint "members_pkey" PRIMARY KEY using index "members_pkey";

alter table "public"."participants" add constraint "participants_pkey" PRIMARY KEY using index "participants_pkey";

alter table "public"."trainings" add constraint "trainings_pkey" PRIMARY KEY using index "trainings_pkey";

alter table "public"."logs" add constraint "logs_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES members(id) not valid;

alter table "public"."logs" validate constraint "logs_memberId_fkey";

alter table "public"."logs" add constraint "logs_trainingId_fkey" FOREIGN KEY ("trainingId") REFERENCES trainings(id) not valid;

alter table "public"."logs" validate constraint "logs_trainingId_fkey";

alter table "public"."participants" add constraint "participants_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES members(id) not valid;

alter table "public"."participants" validate constraint "participants_memberId_fkey";

alter table "public"."participants" add constraint "participants_trainingId_fkey" FOREIGN KEY ("trainingId") REFERENCES trainings(id) not valid;

alter table "public"."participants" validate constraint "participants_trainingId_fkey";

create policy "Enable select/insert/update/delete for authenticated users only"
on "public"."logs"
as permissive
for all
to authenticated
using (true);


create policy "Enable select/insert/update/delete for authenticated users only"
on "public"."members"
as permissive
for all
to authenticated
using (true);


create policy "Enable select/insert/update/delete for authenticated users only"
on "public"."participants"
as permissive
for all
to authenticated
using (true);


create policy "Enable select/insert/update/delete for authenticated users only"
on "public"."trainings"
as permissive
for all
to authenticated
using (true);



-- Views
-- 1. Create View for logs summary
create view view_logs_summary as
  select date, "trainingId", count("memberId") from logs group by date, "trainingId";

-- 2. Create function for checklist
-- drop function get_checklist_members(d text, tId int);
create or replace function get_checklist_members(d text, tId int)
returns table (trainingId int8, memberId int8, lastname text, firstname text, labels jsonb, img text, date text, isMainTrainer boolean) language plpgsql
as
$$
declare
begin
  return query
    select participants."trainingId", participants."memberId", members."lastname", members."firstname", members."labels", members."img", logs."date", logs."isMainTrainer"
    from participants
    full outer join logs on participants."memberId" = logs."memberId" and logs."date" = $1 and logs."trainingId" = $2
    inner join members on members.id =  participants."memberId"
    where participants."trainingId" = $2;
end;
$$;
-- select * from get_checklist_members(text '2022-12-19', 47);

-- 3. Create View to faciliate seaching members
create view view_search_members as
  select id, concat(lastname, ' ', firstname) as fullname, firstname, lastname from members;

-- 4. Create functions for stats
-- drop function get_top_athletes(d text);
create or replace function get_top_athletes(year text)
returns table (memberId int8, lastname text, firstname text, count bigint) language plpgsql
as
$$
declare
begin
  return query
select logs."memberId", members.lastname, members.firstname, count(*)
    from logs
    inner join members on members."id" = logs."memberId"
    where logs."date" like CONCAT($1, '%')
    group by logs."memberId", members.lastname, members.firstname
    order by count desc;
end;
$$;
--select * from get_top_athletes(text '2022');
